Fix: Allow indented comments when parsing.
rigetti/quil-rust pull request #24
Opened 2021-08-10 16:35 UTC by dbanty

First time using `nom` so let me know if there's a cleaner way to do this.

2021-08-10 18:35 UTC, genos approved these changes
Nicely done!

2021-08-11 20:10 UTC, ameyer-rigetti approved these changes

2021-08-12 05:10 UTC, kalzoo requested changes
Good fix!

2021-08-12 05:10 UTC, kalzoo commented on src/parser/common.rs
> +        preceded(many0(token!(Indentation)), value((), token!(Comment(v)))),
Looks like this can just replace line 216

2021-08-12 16:34 UTC, dbanty commented on src/parser/common.rs
> +mod describe_skip_newlines_and_comments {
Actually it's [Jasmine](https://jasmine.github.io/) influence, but it wouldn't surprise me if Jasmine was inspired by rspec.

2021-08-12 16:39 UTC, kalzoo approved these changes

2021-08-12 17:09 UTC, merged